[package]
name = "skw-auth-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skw-mpc-storage = { path="../../storage/skw-mpc-storage" }
skw-mpc-leveldb = { path="../../storage/skw-mpc-leveldb" }

skw-mpc-auth = { path="../../crates/skw-mpc-auth" }

async-std = { version = "1.6.0", features = ["attributes", "tokio1"] }
futures = "0.3.25"
serde = { version = "1.0", features = ["derive"] }
tide = "0.16.0"
serde_json = "1.0.91"
rand = "0.8.5"
hmac-sha1 = "0.1.3"
blake2 = "0.10.6"
http = "0.2.8"
reqwest = { version = "0.11.14", features = ["json"] }
dotenv = "0.15.0"
hex = "0.4.3"
env_logger = "0.10.0"
log = "0.4.17"

[[bin]]
name = "skw-auth-service"