[package]
name = "skw-mpc-client-bin"
version = "0.1.7"
edition = "2021"
authors = ["Song Zhou <song.zhou@skye.kiwi>"]
license = "GPL-3.0"
description = "Mpc node runner"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
skw-mpc-node = { path = "../../crates/skw-mpc-node", default-features = false, features = ["light-node", "tcp-ws-transport"]}
skw-mpc-client = { path = "../../crates/skw-mpc-client" }

futures = "0.3.1"

tokio = { version = "1.25", default-features = false, features = ["rt", "macros"] }

log = "0.4.17"
pretty_env_logger = "0.4.0"

[[bin]]
name = "skw-mpc-client-bin"